### ISSUE TITLE
Feedback for “Ent Schema”. Unclear sentence: This is a 1:many edge because the edges (plural) method is used on the "users" ent and the ref: true option is specified.

### ISSUE THREAD

**Issue by cathedral-on-the-moon** [xixixao/convex-ents#34]
**Observed documentation**
https://labs.convex.dev/convex-ents/schema#1many-edges
"This is a 1:many edge because the edges (plural) method is used on the "users" ent and the ref: true option is specified."

I have a difficult time understanding this sentence.

**Question**
1) What is the purpose of ref: true?
2) In order to create a 1:many edge, must the developer use 
- the edges() function, as opposed to edge() function, 
- and also set the option ref: true?
3) So, if the developer uses the edges() function and does not include the ref: true option, is a 1:many edge still created?
4) Is there a scenario where a developer uses the the edge() function and the ref:true option?
5) Is there a scenario where a developer uses the the edges() function but does not include the ref:true option?

**Comment by xixixao** [comment]
1. It tells TypeScript that these edges are tied to a foreign key reference stored on the other table (instead of `ref: true` you can also do `ref: "someFieldName"`)
2. yes
3. No, the library will try to declare a many:many edge (but the inverse edge must be declared, otherwise you get an error)
4. No, for 1:1 edges `optional: true` is required and implies `ref: true`
5. many:many edges
